/** @type {import('tailwindcss').Config} */
export default {
  content: ['./*.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#00103e',
        'primary-container': '#0a2463',
        'primary-deep': '#00103e',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b5c4ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00164d',
        'on-primary-fixed-variant': '#2e4382',
        'on-primary-container': '#7a8ed2',
        'inverse-primary': '#b5c4ff',
        'secondary': '#755b00',
        'secondary-container': '#fccc38',
        'secondary-fixed': '#ffdf90',
        'secondary-fixed-dim': '#f0c12c',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6f5600',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#584400',
        'tertiary': '#131516',
        'tertiary-container': '#282a2a',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#8f9191',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'background': '#faf8ff',
        'on-background': '#1b1b20',
        'surface': '#faf8ff',
        'surface-dim': '#dbd9df',
        'surface-bright': '#faf8ff',
        'surface-tint': '#475b9c',
        'surface-variant': '#e3e2e8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f9',
        'surface-container': '#efedf3',
        'surface-container-high': '#e9e7ed',
        'surface-container-highest': '#e3e2e8',
        'on-surface': '#1b1b20',
        'on-surface-variant': '#444650',
        'inverse-surface': '#303035',
        'inverse-on-surface': '#f2f0f6',
        'outline': '#757681',
        'outline-variant': '#c5c6d2',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'stack-sm': '8px',
        'gutter': '24px',
        'section-padding': '80px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
        h1: ['Plus Jakarta Sans'],
        h2: ['Plus Jakarta Sans'],
        h3: ['Plus Jakarta Sans'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['36px', { lineHeight: '1.3', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
